// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMRg40eqMlOVmuVZqnfxLjuBKwFr9qb0',
    appId: '1:643946038644:web:a35bbb5dc52c2f01dad821',
    messagingSenderId: '643946038644',
    projectId: 'test-dee6a',
    authDomain: 'test-dee6a.firebaseapp.com',
    storageBucket: 'test-dee6a.firebasestorage.app',
    measurementId: 'G-FZJBH3ET6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLqaUlgIpsyUCQ_SBFTfaTEkwAni-XmI',
    appId: '1:643946038644:android:11287e0f1a338857dad821',
    messagingSenderId: '643946038644',
    projectId: 'test-dee6a',
    storageBucket: 'test-dee6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdchHyCd94YRmji2p1n8K5k4KMDWR15k',
    appId: '1:643946038644:ios:d5e10757f1e7d627dad821',
    messagingSenderId: '643946038644',
    projectId: 'test-dee6a',
    storageBucket: 'test-dee6a.firebasestorage.app',
    iosBundleId: 'com.firebase.demotest.firebaseDemoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxMRg40eqMlOVmuVZqnfxLjuBKwFr9qb0',
    appId: '1:643946038644:web:792a1c56352fbe8ddad821',
    messagingSenderId: '643946038644',
    projectId: 'test-dee6a',
    authDomain: 'test-dee6a.firebaseapp.com',
    storageBucket: 'test-dee6a.firebasestorage.app',
    measurementId: 'G-B8WEQFDV5S',
  );
}
